### PR TITLE
bankapp: improve file structure of the api package

### PR DESCRIPTION
**Pull request by iliyanmotovski**
Changed the api folder structure, aswell as the api tests.

### CODE REVIEW

**Comment by mgenov** [comment]
You need to squash your commits.

**Comment by iliyanmotovski** [comment]
There is a conflict somewhere. I will resolve it.

**Comment by iliyanmotovski** [comment]
Ready for review.

**Review by mgenov — APPROVED** [review]
LGTM ! 

You have to improve the commit messages, cause they are looking messy.

**Pull request merged**
